const categories = [
  'Brands of Toilet Paper',
  'Spicy Foods',
  'Superheroes',
  'Reasons to Sing',
  'Things You Dip in Ketchup',
  'Farm Animals',
  'Zoo Animals',
  'Things with Pockets',
  'Things that start with Q',
  'Things that Spin',
  'Things with Screens',
  'Emotions',
  'Condiments',
  'Terms of Endearment',
  'Viruses',
  'Breakfast Foods',
  'Love Songs',
  'Patriotic Songs',
  'Homework Excuses',
  'Twilight Books',
  'Harry Potter Books',
  'Pizza Toppings',
  'Ice Cream Flavors',
  'Programming Languages',
  'Football Teams',
  'Basketball Teams',
  'Christmas Traditions',
  'Easter Candies',
  'Pokemon',
  'Disney Princesses',
  'Disney Villians',
  'Toy Story Characters',
  'Mountains',
  'Rivers',
  'US Capitals',
  'Parts of Speech',
  'Metric Systems Units',
  'Snow Cone Flavors',
  'Koolaid Flavors',
  'Board Games',
  'Video Games',
  'Things in a Mall',
  'Novelists',
  'Countries in Africa',
  'US Presidents',
  'Things that Have Buttons',
  'Titles People Can Have',
  'Reasons to Make a Phone Call',
  'Types of Chips',
  'Things You Can Buy at IKEA',
  'Brands of Soda',
  'Wildflowers',
  'Waterfalls',
  'Moon Phases',
  'Composers',
  'Types/Flavors of Oreos',
  'Fads',
  'Things Worn Above the Waist',
  'Things Worn Below the Waist',
  'Woodwind Instruments',
  'Musicals',
  'Brass Instruments',
  'Percussion Instruments',
  'String Instruments',
  'Kitchen Appliances',
  'Kitchen Utencils',
  'Lakes',
  'Ford Cars',
  'Toyota Cars',
  'Hostess Brand Products',
  'Wedding Traditions',
  'Harry Potter Characters',
  'Lord of the Rings Characters',
  'Books of the Bible',
  'Dog Breeds',
  'Christmas Carols',
  'Types of Birds',
  'Breakfast Cereals',
  'Types of Donuts',
  'Countries South of the Equator',
  'Animal Cartoon Characters',
  'Orphans in Literature',
  'Toothpaste Brands',
  'Candy Bars',
  'Colors in the Rainbow',
  'Charlie Brown Specials',
  'Charlie Brown Characters',
  'Things You Get in the Mail',
  'Things You Shouldn\'t Touch',
  'People in the Simpsons',
  'Foreign Words Now Used in English',
  'Kinds of Soup',
  'Things You Throw Away',
  'Famous Duos & Trios',
  'Novels by Jane Austen',
  'Novels by Charles Dickens',
  'Characters in A Christmas Carol',
  'Things You Replace',
  'Words Associated With Exercise',
  'Reptiles',
  'Amphibians',
  'Spices & Herbs',
  'Magazines',
  'Sticky Things',
  'Animals in Books',
  'Animals in Movies',
  'Food Eaten Raw',
  'Children\'s Books',
  'Mobile Apps',
  'Things in a Sandwich',
  'Types of Cookies',
  'Types of Pie',
  'Types of Lunchmeat',
  'Types of Cheese'
]
