const gameWords = [
  'wheel',
  'wheel of fortune',
  'jeopardy',
  'tic-tac-toe',
  'nine square',
  'board',
  'video',
  'pictionary',
  'nintendo',
  'x-box',
  'game boy',
  'game',
  'code names',
  'hide-n-seek',
  'capture the flag',
  'fun',
  'social',
  'words', 'tiles',
  'spymaster',
  'spies',
  'mafia',
  'rivals',
  'competition',
  'tournament',
  'team',
  'teammates',
  'teammate',
  'compete',
  'rounds',
  'matches',
  'draw',
  'guess',
  'mystery',
  'points',
  'winner',
  'winners',
  'loser',
  'losers',
  'tie',
  'end game',
  'crown',
  'multiplayer',
  'online',
  'party',
  'trivia',
  'knowledge',
  'quiz',
  'friends',
  'telephone game',
  'hilarious',
  'brainy',
  'zoom',
  'rules',
  'cards',
  'deck of cards',
  'dice',
  'spinner',
  'game board',
  'score',
  'instructions',
  'monopoly',
  'yahtzee',
  'game of life',
  'risk',
  'gamble',
  'chutes and ladders',
  'candyland',
  'invite',
  'taboo',
  'judge',
  'timer',
  'jigsaw puzzle',
  'puzzle',
  'play',
  'tetris',
  'farm town',
  'controls',
  'family feud',
  'questions',
  'answers',
  'hearts',
  'spades',
  'diamonds',
  'clubs',
  'uno',
  'crazy eights',
  'wordle',
  'turns',
  'clue',
  'colonel mustard',
  'miss scarlet',
  'professor plum',
  'mr boddy',
  'mrs peacock',
  'mr green',
  'mrs white',
  'scrabble',
  'battleship',
  'alliances',
  'conquer',
  'settlers of catan',
  'chess',
  'king',
  'queen',
  'pawn',
  'knight',
  'bishop',
  'checkers',
  'backgammon',
  'chinese checkers',
  'connect four',
  'twister',
  'operation',
  'hungry hungry hippos',
  'boggle',
  'mouse trap',
  'jenga',
  'dominoes',
  'trouble',
  'ticket to ride',
  'sorry',
  'apples to apples',
  'scattergories',
  'mad libs',
  'trivial pursuit',
  'pandemic',
  'guess who',
  'farkle',
  'hi ho cherry-o',
  'splendor',
  'exploding kittens',
  'throw throw burrito',
  'werewolf',
  'rack-o',
  'oregon trail',
  'dungeons and dragons',
  'cleric',
  'fighter',
  'magic user',
  'thief',
  'cheat',
  'cheater',
  'dwarf',
  'elf',
  'halfling',
  'name that tune',
  'klondike',
  'go fish',
  'rummy',
  'old maid',
  'poker',
  'war',
  'cribbage',
  'euchre',
  'egyptian ratscrew',
  'golf',
  'scum',
  'spoons',
  'bridge',
  'pinochle',
  'rook',
  'whist',
  'nertz',
  'solitaire',
  'minesweeper',
  'texas hold\'em',
  'canasta',
  'black jack',
  'family time',
  'card table',
  'bell',
  'wii sports',
  'mario',
  'luigi',
  'princess peach',
]
