const items = [
  'toothbrush',
  'computer',
  'washing machine',
  'microwave',
  'hair',
  'feet',
  'teeth',
  'sunglasses',
  'license plate',
  'car',
  'house',
  'swimsuit',
  'pajamas',
  'favorite dessert',
  'favorite magazine',
  'favorite movie',
  'favorite TV show',
  'favorite singer',
  'neighbor',
  'mom',
  'dad',
  'grandma',
  'grandpa',
  'lawn mower',
  'bedroom',
  'bathroom',
  'shower',
  'sink',
  'water bottle',
  'phone',
  'toothpaste',
  'shampoo',
  'front door',
  'yard',
  'fridge',
  'bed',
  'eyes',
  'nose',
  'knees',
  'fingernails',
  'toenails',
  'breath',
  'tongue',
  'sense of humor',
  'favorite sport',
  'favorite ice cream',
  'favorite breakfast',
  'favorite toy',
  'plant',
  'pet',
  'aunt',
  'uncle',
  'sibling',
  'clock',
  'hat',
  'jacket',
  'coat',
  'favorite store',
  'statue',
  'bag',
  'painting',
  'spirit animal',
]
