const gamesWithUrls = [
        { "name": "Dixit", "url": "https://www.amazon.com/s?k=Dixit+board+game" },
        { "name": "Codenames", "url": "https://www.amazon.com/s?k=Codenames+board+game" },
        { "name": "Bananagrams", "url": "https://www.amazon.com/s?k=Bananagrams+board+game" },
        { "name": "Exploding Kittens", "url": "https://www.amazon.com/s?k=Exploding+Kittens+card+game" },
        { "name": "Monopoly Deal", "url": "https://www.amazon.com/s?k=Monopoly+Deal+card+game" },
        { "name": "Monopoly", "url": "https://www.amazon.com/s?k=Monopoly+board+game" },
        { "name": "Clue", "url": "https://www.amazon.com/s?k=Clue+board+game" },
        { "name": "Harry Potter Clue", "url": "https://www.amazon.com/s?k=Harry+Potter+Clue+board+game" },
        { "name": "UNO", "url": "https://www.amazon.com/s?k=UNO+card+game" },
        { "name": "UNO No Mercy", "url": "https://www.amazon.com/s?k=UNO+No+Mercy+card+game" },
        { "name": "Wits and Wagers", "url": "https://www.amazon.com/s?k=Wits+and+Wagers+board+game" },
        { "name": "Wits and Wagers Family Edition", "url": "https://www.amazon.com/s?k=Wits+and+Wagers+Family+Edition+board+game" },
        { "name": "Funglish", "url": "https://www.amazon.com/s?k=Funglish+board+game" },
        { "name": "That's Not a Hat: Pop Culture Edition", "url": "https://www.amazon.com/s?k=Thats+Not+a+Hat+Pop+Culture+Edition+card+game" },
        { "name": "Ticket to Ride", "url": "https://www.amazon.com/s?k=Ticket+to+Ride+board+game" },
        { "name": "Boggle", "url": "https://www.amazon.com/s?k=Boggle+board+game" },
        { "name": "Chess", "url": "https://www.amazon.com/s?k=Chess+board+game" },
        { "name": "Catan", "url": "https://www.amazon.com/s?k=Catan+board+game" },
        { "name": "Apples to Apples", "url": "https://a.co/d/6i9q97g" },
        { "name": "Telestrations", "url": "https://www.amazon.com/s?k=Telestrations+board+game" },
        { "name": "Pandemic", "url": "https://www.amazon.com/s?k=Pandemic+board+game" },
        { "name": "The Game of Life", "url": "https://www.amazon.com/s?k=The+Game+of+Life+board+game" },
        { "name": "Scattergories", "url": "https://www.amazon.com/s?k=Scattergories+board+game" },
        { "name": "Sushi Go", "url": "https://www.amazon.com/s?k=Sushi+Go+card+game" },
        { "name": "Throw Throw Burrito", "url": "https://www.amazon.com/s?k=Throw+Throw+Burrito+card+game" },
        { "name": "Taco Cat Goat Cheese Pizza", "url": "https://www.amazon.com/s?k=Taco+Cat+Goat+Cheese+Pizza+card+game" },
        { "name": "Herd Mentality", "url": "https://www.amazon.com/s?k=Herd+Mentality+board+game" },
        { "name": "Hues and Cues", "url": "https://www.amazon.com/s?k=Hues+and+Cues+board+game" },
        { "name": "Phase 10", "url": "https://www.amazon.com/s?k=Phase+10+card+game" },
        { "name": "Forbidden Island", "url": "https://www.amazon.com/s?k=Forbidden+Island+board+game" },
        { "name": "Rummikub", "url": "https://www.amazon.com/s?k=Rummikub+board+game" },
        { "name": "Quirkle", "url": "https://www.amazon.com/s?k=Quirkle+board+game" },
        { "name": "Secret Hitler", "url": "https://www.amazon.com/s?k=Secret+Hitler+board+game" },
        { "name": "Mille Bourns", "url": "https://www.amazon.com/s?k=Mille+Borne+card+game" },
        { "name": "Coup", "url": "https://www.amazon.com/s?k=Coup+card+game" },
        { "name": "Hungry Hungry Hippos", "url": "https://www.amazon.com/s?k=Hungry+Hungry+Hippos+board+game" },
        { "name": "Risk", "url": "https://www.amazon.com/s?k=Risk+board+game" },
        { "name": "Bears vs Babies", "url": "https://www.amazon.com/s?k=Bears+vs+Babies+card+game" },
        { "name": "Word on the Street", "url": "https://www.amazon.com/s?k=Word+on+the+Street+board+game" },
        { "name": "Kids Against Maturity", "url": "https://www.amazon.com/s?k=Kids+Against+Maturity+card+game" },
        { "name": "DiagnosThis", "url": "https://www.amazon.com/s?k=DiagnosThis+card+game" },
        { "name": "Cover Your A$$ets", "url": "https://www.amazon.com/s?k=Cover+Your+A$$ets+card+game" },
        { "name": "We Didn't Playtest This At All", "url": "https://www.amazon.com/s?k=We+Didnt+Playtest+This+At+All+card+game" },
        { "name": "Tenzi", "url": "https://www.amazon.com/s?k=Tenzi+dice+game" },
        { "name": "You've Got Crabs", "url": "https://www.explodingkittens.com/pages/rules-youve-got-crabs" },
        { "name": "Stuff Happens", "url": "https://a.co/d/gSPxc43" },
        { "name": "Blink", "url": "https://a.co/d/ff78ZSo" },
        { "name": "Chronology", "url": "https://a.co/d/aKR4IuF" },
        { "name": "Coup", "url": "https://a.co/d/3NFql8t" },
        { "name": "Pick Your Poison", "url": "https://a.co/d/3cYMlhA" },
        { "name": "Creationary", "url": "https://boardgamegeek.com/boardgame/41833/creationary" },
        { "name": "Say Anything Family Edition", "url": "https://a.co/d/cfsWC6x" },
        { "name": "Snake Oil", "url": "https://www.snakeoilgame.com/" },
        { "name": "Control", "url": "https://keymaster.fun/products/control" },
        { "name": "Hoopla", "url": "https://a.co/d/40qBnLv" },
        { "name": "Reverse Charades", "url": "https://a.co/d/eIfeXBZ" },
        { "name": "Blokus", "url": "https://a.co/d/6zKJ6Oz" },
        { "name": "The Castles of Burgundy", "url": "https://a.co/d/cRXTtL0" },
        { "name": "Wordsmith", "url": "https://a.co/d/efzKiua" },
        { "name": "Quick Cups", "url": "https://a.co/d/09T9BNT" },
        { "name": "A Little Wordy", "url": "https://www.explodingkittens.com/pages/rules-a-little-wordy" },
        { "name": "Dan Ariely's Irrational Game", "url": "https://boardgamegeek.com/boardgame/187033/irrational-game" },
        { "name": "Bye, Felicia", "url": "https://a.co/d/azJ2uog" },
        { "name": "Watch Ya Mouth", "url": "https://a.co/d/0kcn878" },
        { "name": "Curses", "url": "https://a.co/d/hr7VM4j" },
        { "name": "Jenga", "url": "https://a.co/d/dOzk3SA" },
        { "name": "Conversation Jenga", "url": "" },
        { "name": "Discombobulation", "url": "https://boardgamegeek.com/boardgame/32645/discombobulation" },
        { "name": "Catan Dice", "url": "https://www.catan.com/dice-game" },
        { "name": "Monopoly Pokemon Edition", "url": "https://www.hasbropulse.com/product/monopoly-pok%C3%A9mon-edition/G07160000" },
        { "name": "Kid History", "url": "https://boardgamegeek.com/boardgame/176158/kid-history-the-party-game" },
        { "name": "Mad Gab", "url": "https://a.co/d/6myianl" },
        { "name": "Spot It!", "url": "https://www.spotitgame.com/" },
        { "name": "Shut the Box", "url": "https://www.mastersofgames.com/rules/shut-box-rules.htm" },
        { "name": "Last Word", "url": "https://boardgamegeek.com/boardgame/17709/last-word" },
        { "name": "Camp", "url": "https://boardgamegeek.com/boardgame/28010/camp" },
        { "name": "In a Pickle", "url": "https://gamewright.com/product/In-a-Pickle" },
        { "name": "Boxers vs Briefs", "url": "https://a.co/d/h7jbVC7" },
        { "name": "Toss Your Cookies", "url": "https://gamewright.com/product/Toss-Your-Cookies" },
        { "name": "Infiltation", "url": "https://boardgamegeek.com/boardgame/118063/android-infiltration" },
        { "name": "Stupor", "url": "" },
        { "name": ":59 Seconds", "url": "https://www.universitygames.com/59seconds" },
        { "name": "Bop It", "url": "https://www.universitygames.com/59seconds" },
        { "name": "Chess", "url": "" },
        { "name": "WereWords", "url": "https://werewords.com/rules.php?ver=3" },
        { "name": "5 Second Rule", "url": "https://a.co/d/6i9q97g" },
    ]
    
