const games = [
    'Dixit',
    'Codenames',
    'Bananagrams',
    'Exploding Kittens',
    'Monopoly Deal',
    'Monopoly',
    'Clue',
    'Harry Potter Clue',
    'UNO',
    'UNO No Mercy',
    'Wits and Wagers',
    'Wits and Wagers Family Edition',
    'Funglish',
    'That\'s Not a Hat: Pop Culture Edition',
    'Ticket to Ride',
    'Boggle',
    'Chess',
    'Catan',
    'Apples to Apples',
    'Telestrations',
    'Pandemic',
    'The Game of Life',
    'Scattergories',
    'Sushi Go',
    'Throw Throw Burrito',
    'Taco Cat Goat Cheese Pizza',
    'Herd Mentality',
    'Hues and Cues',
    'Phase 10',
    'Forbidden Island',
    'Rummikub',
    'Quirkle',
    'Secret Hitler',
    'Mille Borne',
    'Coup',
    'Hungry Hungry Hippos',
    'Risk',
    'Bears vs Babies',
    'Word on the Street',
    'Kids Against Maturity',
    'DiagnosThis',
    'Cover Your A$$ets',
    'We Didn\'t Playtest This At All',
    'Kids Against Maturity',
    'Tenzi',
]

const gamesWithUrls = [
        { "name": "Dixit", "url": "https://www.amazon.com/s?k=Dixit+board+game" },
        { "name": "Codenames", "url": "https://www.amazon.com/s?k=Codenames+board+game" },
        { "name": "Bananagrams", "url": "https://www.amazon.com/s?k=Bananagrams+board+game" },
        { "name": "Exploding Kittens", "url": "https://www.amazon.com/s?k=Exploding+Kittens+card+game" },
        { "name": "Monopoly Deal", "url": "https://www.amazon.com/s?k=Monopoly+Deal+card+game" },
        { "name": "Monopoly", "url": "https://www.amazon.com/s?k=Monopoly+board+game" },
        { "name": "Clue", "url": "https://www.amazon.com/s?k=Clue+board+game" },
        { "name": "Harry Potter Clue", "url": "https://www.amazon.com/s?k=Harry+Potter+Clue+board+game" },
        { "name": "UNO", "url": "https://www.amazon.com/s?k=UNO+card+game" },
        { "name": "UNO No Mercy", "url": "https://www.amazon.com/s?k=UNO+No+Mercy+card+game" },
        { "name": "Wits and Wagers", "url": "https://www.amazon.com/s?k=Wits+and+Wagers+board+game" },
        { "name": "Wits and Wagers Family Edition", "url": "https://www.amazon.com/s?k=Wits+and+Wagers+Family+Edition+board+game" },
        { "name": "Funglish", "url": "https://www.amazon.com/s?k=Funglish+board+game" },
        { "name": "That's Not a Hat: Pop Culture Edition", "url": "https://www.amazon.com/s?k=Thats+Not+a+Hat+Pop+Culture+Edition+card+game" },
        { "name": "Ticket to Ride", "url": "https://www.amazon.com/s?k=Ticket+to+Ride+board+game" },
        { "name": "Boggle", "url": "https://www.amazon.com/s?k=Boggle+board+game" },
        { "name": "Chess", "url": "https://www.amazon.com/s?k=Chess+board+game" },
        { "name": "Catan", "url": "https://www.amazon.com/s?k=Catan+board+game" },
        { "name": "Apples to Apples", "url": "https://www.amazon.com/s?k=Apples+to+Apples+card+game" },
        { "name": "Telestrations", "url": "https://www.amazon.com/s?k=Telestrations+board+game" },
        { "name": "Pandemic", "url": "https://www.amazon.com/s?k=Pandemic+board+game" },
        { "name": "The Game of Life", "url": "https://www.amazon.com/s?k=The+Game+of+Life+board+game" },
        { "name": "Scattergories", "url": "https://www.amazon.com/s?k=Scattergories+board+game" },
        { "name": "Sushi Go", "url": "https://www.amazon.com/s?k=Sushi+Go+card+game" },
        { "name": "Throw Throw Burrito", "url": "https://www.amazon.com/s?k=Throw+Throw+Burrito+card+game" },
        { "name": "Taco Cat Goat Cheese Pizza", "url": "https://www.amazon.com/s?k=Taco+Cat+Goat+Cheese+Pizza+card+game" },
        { "name": "Herd Mentality", "url": "https://www.amazon.com/s?k=Herd+Mentality+board+game" },
        { "name": "Hues and Cues", "url": "https://www.amazon.com/s?k=Hues+and+Cues+board+game" },
        { "name": "Phase 10", "url": "https://www.amazon.com/s?k=Phase+10+card+game" },
        { "name": "Forbidden Island", "url": "https://www.amazon.com/s?k=Forbidden+Island+board+game" },
        { "name": "Rummikub", "url": "https://www.amazon.com/s?k=Rummikub+board+game" },
        { "name": "Quirkle", "url": "https://www.amazon.com/s?k=Quirkle+board+game" },
        { "name": "Secret Hitler", "url": "https://www.amazon.com/s?k=Secret+Hitler+board+game" },
        { "name": "Mille Borne", "url": "https://www.amazon.com/s?k=Mille+Borne+card+game" },
        { "name": "Coup", "url": "https://www.amazon.com/s?k=Coup+card+game" },
        { "name": "Hungry Hungry Hippos", "url": "https://www.amazon.com/s?k=Hungry+Hungry+Hippos+board+game" },
        { "name": "Risk", "url": "https://www.amazon.com/s?k=Risk+board+game" },
        { "name": "Bears vs Babies", "url": "https://www.amazon.com/s?k=Bears+vs+Babies+card+game" },
        { "name": "Word on the Street", "url": "https://www.amazon.com/s?k=Word+on+the+Street+board+game" },
        { "name": "Kids Against Maturity", "url": "https://www.amazon.com/s?k=Kids+Against+Maturity+card+game" },
        { "name": "DiagnosThis", "url": "https://www.amazon.com/s?k=DiagnosThis+card+game" },
        { "name": "Cover Your A$$ets", "url": "https://www.amazon.com/s?k=Cover+Your+A$$ets+card+game" },
        { "name": "We Didn't Playtest This At All", "url": "https://www.amazon.com/s?k=We+Didnt+Playtest+This+At+All+card+game" },
        { "name": "Tenzi", "url": "https://www.amazon.com/s?k=Tenzi+dice+game" }
    ]
    
