const openingGoodNews = [
  'I\'ve got a new girl/boy friend!',
  'there\'s a big package for me on the porch!',
  'I\'ve just cured cancer!',
  'I have a new pet dog!',
  'I have a new pet cat!',
  'I have a new pet!',
  'I\'m getting married tomorrow!',
  'I have a new job!',
  'the world has achieved world peace!',
  'I won the lottery!',
  'I won Cupcake Wars!',
  'my friend just became famous!',
  'tomorrow is Christmas!',
  'today is a snow day!',
  '12 pizzas will be delivered to the house in 5 minutes!',
  'I discovered buried treasure yesterday!',
  'I created a living dinosaur!',
  'I invented something to solve all of the world\'s problems!',
  'I invented a pill you can take so you don\'t need to brush your teeth anymore!',
  'my hair no longer falls out.',
  'I won a free makeover!',
  'today is free slurpee day at 7-Eleven!',
  'today is bring-your-own-container day at 7-Eleven!',
  'we discovered alien life!',
  'we discovered a way for dogs to talk to humans.',
  'world hunger is no longer a thing.',
  'the common cold is no longer a thing.',
  'Target is having an incredible sale today.',
  'I met my long-long relative.',
  'Costco has a record number of free samples today.',
  'Mountain Dew just release a new flavor!',
  'It\'s my birthday!',
  'they canceled my least-favorite TV show.',
  'my favorite author just wrote a new book!',
  'school is canceled indefinitely!',
  'I can fly now!',
  'it\'s Amazon Prime Day!',
  'I just saw a butterfly.',
  'I\'m pregnant!',
  'I\'m engaged!',
  'I\'m alive!',
  'I\'m going to space!',
  'There\'s cheese in the fridge.'
]
