const items = [
    'birthday cake', 
    'chainsaw', 
    'teddy bear', 
    'rattlesnake',
    'fat crayon', 
    'beetle collection', 
    'cupcake', 
    'belly button',
    'toothbrush', 
    'gummy shark', 
    'clown wig', 
    'pair of moon boots', 
    'spider',
    'potato', 
    'slice of bacon', 
    'holey sock', 
    'bowtie', 
    'peach pie', 
    'bunny slipper', 
    'rubber chicken', 
    'pet cow', 
    'fidget spinner', 
    'phone booth', 
    'mummy sleeping bag', 
    'ketchup bottle', 
    'porta potty', 
    'q-tip', 
    'split pea soup',
    'Twilight book',
    'stickered water bottle',
    'favorite pair of sunglasses',
    'mixtape',
    'walkman',
]

const actions = [
    'eat it up', 
    'make noise with it', 
    'hug it', 
    'wear it',
    'milk it', 
    'write with it', 
    'scare someone with it',
    'lick it', 
    'admire it', 
    'put toothpaste on it', 
    'stick it on your head', 
    'dance with it', 
    'stick it on my head',
    'fry it in a pan', 
    'name it Fred', 
    'give it a perm', 
    'apply makeup on it',
    'take out its appendix', 
    'plant it in a pot', 
    'take it to a dance', 
    'eat it whole', 
    'build it a house',
    'take it skydiving', 
    'teach it to drive', 
    'bury it',
    'start a fan club about it',
    'send it to you',
    'bedazzle it',
]


